const CONSTANTS = {
  Reset: "\x1b[0m",
  Bright: "\x1b[1m",
  Dim: "\x1b[2m",
  Underscore: "\x1b[4m",
  Blink: "\x1b[5m",
  Reverse: "\x1b[7m",
  Hidden: "\x1b[8m",
  FgBlack: "\x1b[30m",
  FgRed: "\x1b[31m",
  FgGreen: "\x1b[32m",
  FgYellow: "\x1b[33m",
  FgBlue: "\x1b[34m",
  FgMagenta: "\x1b[35m",
  FgCyan: "\x1b[36m",
  FgWhite: "\x1b[37m",
  BgBlack: "\x1b[40m",
  BgRed: "\x1b[41m",
  BgGreen: "\x1b[42m",
  BgYellow: "\x1b[43m",
  BgBlue: "\x1b[44m",
  BgMagenta: "\x1b[45m",
  BgCyan: "\x1b[46m",
  BgWhite: "\x1b[47m",
}

export const Colors = {
  green: (str: string) => `${CONSTANTS.FgGreen}${str}${CONSTANTS.Reset}`,
  red: (str: string) => `${CONSTANTS.FgRed}${str}${CONSTANTS.Reset}`,
  yellow: (str: string) => `${CONSTANTS.FgYellow}${str}${CONSTANTS.Reset}`,
  blue: (str: string) => `${CONSTANTS.FgBlue}${str}${CONSTANTS.Reset}`,
  magenta: (str: string) => `${CONSTANTS.FgMagenta}${str}${CONSTANTS.Reset}`,
  cyan: (str: string) => `${CONSTANTS.FgCyan}${str}${CONSTANTS.Reset}`,
  white: (str: string) => `${CONSTANTS.FgWhite}${str}${CONSTANTS.Reset}`,
  black: (str: string) => `${CONSTANTS.FgBlack}${str}${CONSTANTS.Reset}`,
  bright: (str: string) => `${CONSTANTS.Bright}${str}${CONSTANTS.Reset}`,
  dim: (str: string) => `${CONSTANTS.Dim}${str}${CONSTANTS.Reset}`,
  underscore: (str: string) => `${CONSTANTS.Underscore}${str}${CONSTANTS.Reset}`,
  blink: (str: string) => `${CONSTANTS.Blink}${str}${CONSTANTS.Reset}`,
  reverse: (str: string) => `${CONSTANTS.Reverse}${str}${CONSTANTS.Reset}`,
  hidden: (str: string) => `${CONSTANTS.Hidden}${str}${CONSTANTS.Reset}`,
  bgBlack: (str: string) => `${CONSTANTS.BgBlack}${str}${CONSTANTS.Reset}`,
  bgRed: (str: string) => `${CONSTANTS.BgRed}${str}${CONSTANTS.Reset}`,
  bgGreen: (str: string) => `${CONSTANTS.BgGreen}${str}${CONSTANTS.Reset}`,
  bgYellow: (str: string) => `${CONSTANTS.BgYellow}${str}${CONSTANTS.Reset}`,
  bgBlue: (str: string) => `${CONSTANTS.BgBlue}${str}${CONSTANTS.Reset}`,
  bgMagenta: (str: string) => `${CONSTANTS.BgMagenta}${str}${CONSTANTS.Reset}`,
  bgCyan: (str: string) => `${CONSTANTS.BgCyan}${str}${CONSTANTS.Reset}`,
  bgWhite: (str: string) => `${CONSTANTS.BgWhite}${str}${CONSTANTS.Reset}`,
} as { [key: string]: (str: string) => string }
